server:
    port: 8080

baseUrl: http://localhost:${server.port}

spring:
    profiles:
        active: dev
    data:
        mongodb:
            host: localhost
            port: 27017
            database: hoozad
    social:
        facebook:
                 clientId: 472039716296566
                 clientSecret: bceb8b649c82f0fc3703cfb9cedcf902

    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: hoozad


