spring:
    profiles:
        active: dev
    data:
        mongodb:
            host: ds061370.mongolab.com
            port: 61370
            database: hoozad
            username: hoozad
            password: h00zad
    social:
        facebook:
                 clientId: 472040512963153
                 clientSecret: f3dc6cc255c9ff82bb4a5658506a3ace
    mail:
        baseUrl: http://localhost:${server.port}

    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: hoozad


