# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: hoozad

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

spring:
    messageSource:
        cacheSeconds: 1

    social:
        facebook:
                 clientId: 460033100830561
                 clientSecret: acc280110fa26ea8766d073fb17cacb8

swagger:
    title: hoozad API
    description: hoozad applications and beyond!
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
